### ISSUE TITLE
Loading linux musl addon Error: Cannot find module '@node-rs/bcrypt-linux-musl'

### ISSUE THREAD

**Issue by coderaiser** [napi-rs/node-rs#361]
After installing on alpine docker container, I see such an error:

```
Loading linux musl addon Error: Cannot find module '@node-rs/bcrypt-linux-musl'
Require stack:
- /usr/src/app/node_modules/@node-rs/helper/lib/loader.js
- /usr/src/app/node_modules/@node-rs/helper/lib/index.js
- /usr/src/app/node_modules/@node-rs/bcrypt/index.js
- /usr/src/app/node_modules/http-auth/src/auth/basic.js
- /usr/src/app/node_modules/http-auth/src/http-auth.js
```

Could you please help me to handle it.

**Comment by Brooooooklyn** [comment]
Have you installed dependencies with `--ignore-optional` flag?
Check if `node_modules/@node-rs/bcrypt-linux-x64-musl/bcrypt.linux-x64-musl.node` existed in your container.

**Comment by coderaiser** [comment]
> Have you installed dependencies with --ignore-optional flag?

I have installed packages with [--production flag](https://github.com/coderaiser/cloudcmd/blob/v15.9.2/docker/Dockerfile.alpine#L10)

> Check if node_modules/@node-rs/bcrypt-linux-x64-musl/bcrypt.linux-x64-musl.node existed in your container.

Could you please advice me how to check this, I running `docker container` using:
```
coderaiser@cloudcmd:~/iocmd$ docker run -t -v ~:/root -v /:/mnt/fs -w=/root -p 8000:8000 coderaiser/cloudcmd:latest-alpine
```

And it is crashed with:

```
Loading linux musl addon Error: Cannot find module '@node-rs/bcrypt-linux-musl'
Require stack:
- /usr/src/app/node_modules/@node-rs/helper/lib/loader.js
- /usr/src/app/node_modules/@node-rs/helper/lib/index.js
- /usr/src/app/node_modules/@node-rs/bcrypt/index.js
- /usr/src/app/node_modules/http-auth/src/auth/basic.js
- /usr/src/app/node_modules/http-auth/src/http-auth.js
- /usr/src/app/server/auth.js
- /usr/src/app/server/cloudcmd.js
- /usr/src/app/server/server.js, Loading linux addon Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/src/app/node_modules/@node-rs/bcrypt-linux/bcrypt.linux.node) Promise {
  <rejected> TypeError: Loading linux musl addon Error: Cannot find module '@node-rs/bcrypt-linux-musl'
  Require stack:
  - /usr/src/app/node_modules/@node-rs/helper/lib/loader.js
  - /usr/src/app/node_modules/@node-rs/helper/lib/index.js
  - /usr/src/app/node_modules/@node-rs/bcrypt/index.js
  - /usr/src/app/node_modules/http-auth/src/auth/basic.js
  - /usr/src/app/node_modules/http-auth/src/http-auth.js
  - /usr/src/app/server/auth.js
  - /usr/src/app/server/cloudcmd.js
  - /usr/src/app/server/server.js, Loading linux addon Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/src/app/node_modules/@node-rs/bcrypt-linux/bcrypt.linux.node)
      at loadBinding (/usr/src/app/node_modules/@node-rs/helper/lib/loader.js:45:27)
      at Object.<anonymous> (/usr/src/app/node_modules/@node-rs/bcrypt/index.js:3:17)
      at Module._compile (node:internal/modules/cjs/loader:1092:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
      at Module.load (node:internal/modules/cjs/loader:972:32)
      at Function.Module._load (node:internal/modules/cjs/loader:813:14)
      at Module.require (node:internal/modules/cjs/loader:996:19)
      at require (node:internal/modules/cjs/helpers:92:18)
      at Object.<anonymous> (/usr/src/app/node_modules/http-auth/src/auth/basic.js:16:16)
      at Module._compile (node:internal/modules/cjs/loader:1092:14)
}
```

And then I see:

```sh
coderaiser@cloudcmd:~/iocmd$ docker ps -a
CONTAINER ID   IMAGE                               COMMAND                  CREATED         STATUS                     PORTS     NAMES
e4256deac322   coderaiser/cloudcmd:latest-alpine   "/usr/src/app/bin/cl…"   5 seconds ago   Exited (1) 2 seconds ago             peaceful_dijkstra
```

**Comment by Brooooooklyn** [comment]
@node-rs/bcrypt 1.x fixed compatible issue with alpine Linux，upgrade it from http-auth will resolve this problem.
