### ISSUE TITLE
How to ensure my Rust environment is setup right for this repo?

### ISSUE THREAD

**Issue by mohsen1** [napi-rs/node-rs#614]
Hi, 

N00b Rust learner here. I'm trying to build the packages in main (3e555f1) using `yarn build` and getting the following error:

<details>

```
 ~/C/node-rs    yarn build                                             36.3s  Tue Jan 18 13:52:57 2022
yarn run v1.22.11
$ lerna run build --concurrency 1 --stream --no-prefix
lerna notice cli v4.0.0
lerna info versioning independent
lerna info Executing command in 7 packages: "yarn run build"
$ napi build --platform --release --pipe "prettier -w"
   Compiling cfg-if v1.0.0
   Compiling libc v0.2.112
   Compiling autocfg v1.0.1
   Compiling typenum v1.15.0
   Compiling lazy_static v1.4.0
   Compiling proc-macro2 v1.0.36
   Compiling version_check v0.9.4
   Compiling crossbeam-utils v0.8.6
error: the option `Z` is only accepted on the nightly compiler
error: the option `Z` is only accepted on the nightly compiler
error: the option `Z` is only accepted on the nightly compiler
error: the option `Z` is only accepted on the nightly compiler
error: the option `Z` is only accepted on the nightly compiler
error: the option `Z` is only accepted on the nightly compiler
error: the option `Z` is only accepted on the nightly compiler
error: the option `Z` is only accepted on the nightly compiler
error: could not compile `typenum`
warning: build failed, waiting for other jobs to finish...
error: build failed
Internal Error: Command failed: cargo build --release
    at checkExecSyncError (child_process.js:635:11)
    at Object.execSync (child_process.js:671:15)
    at BuildCommand.<anonymous> (/Users/mohsen_azimi/Code/node-rs/node_modules/@napi-rs/cli/scripts/index.js:12797:26)
    at Generator.next (<anonymous>)
    at /Users/mohsen_azimi/Code/node-rs/node_modules/@napi-rs/cli/scripts/index.js:1678:71
    at new Promise (<anonymous>)
    at __awaiter$1 (/Users/mohsen_azimi/Code/node-rs/node_modules/@napi-rs/cli/scripts/index.js:1674:12)
    at BuildCommand.execute (/Users/mohsen_azimi/Code/node-rs/node_modules/@napi-rs/cli/scripts/index.js:12721:16)
    at BuildCommand.validateAndExecute (/Users/mohsen_azimi/Code/node-rs/node_modules/@napi-rs/cli/scripts/index.js:204:37)
    at /Users/mohsen_azimi/Code/node-rs/node_modules/@napi-rs/cli/scripts/index.js:1261:53
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build exited 1 in '@node-rs/argon2'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 !  ~/C/node-rs                                                      2766ms  Tue Jan 18 13:53:02 2022
```

</details>

My Rust versions:

<details>

<summary><code>rustup show</code></summary>

```
Default host: x86_64-apple-darwin
rustup home:  /Users/mohsen_azimi/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
nightly-2021-12-05-x86_64-apple-darwin

active toolchain
----------------

nightly-2021-12-05-x86_64-apple-darwin (overridden by '/Users/mohsen_azimi/Code/node-rs/rust-toolchain')
rustc 1.59.0-nightly (efec54529 2021-12-04)
```

</details>

**Comment by Brooooooklyn** [comment]
Seems like your `Cargo` didn't respect the [rust-toolchain](https://github.com/napi-rs/node-rs/blob/main/rust-toolchain) file. Try to run `rustup default nightly` and run build again.

**Comment by mohsen1** [comment]
Thank you! I'm using Fish Shell and Rust is not entirely happy with it. After some try and error got my Rust installation in a better shape. 

After setting my default to `nightly` I am getting a diff with `yarn build` which is not usual but I will ignore it for now:

<details> 

<summary>diff</summary>

```diff
diff --git packages/argon2/index.js packages/argon2/index.js
index cc586be..a201923 100644
--- packages/argon2/index.js
+++ packages/argon2/index.js
@@ -17,7 +17,7 @@ function isMusl() {
     }
   } else {
     const { glibcVersionRuntime } = process.report.getReport().header
-    return !glibcVersionRuntime
+    return !Boolean(glibcVersionRuntime)
   }
 }
 
diff --git packages/bcrypt/index.js packages/bcrypt/index.js
index 0458067..b770359 100644
--- packages/bcrypt/index.js
+++ packages/bcrypt/index.js
@@ -17,7 +17,7 @@ function isMusl() {
     }
   } else {
     const { glibcVersionRuntime } = process.report.getReport().header
-    return !glibcVersionRuntime
+    return !Boolean(glibcVersionRuntime)
   }
 }
 
diff --git packages/deno-lint/index.js packages/deno-lint/index.js
index fa07c62..8fa3bac 100644
--- packages/deno-lint/index.js
+++ packages/deno-lint/index.js
@@ -17,7 +17,7 @@ function isMusl() {
     }
   } else {
     const { glibcVersionRuntime } = process.report.getReport().header
-    return !glibcVersionRuntime
+    return !Boolean(glibcVersionRuntime)
   }
 }
 
diff --git packages/jieba/index.js packages/jieba/index.js
index 4f67e8d..39e5d0a 100644
--- packages/jieba/index.js
+++ packages/jieba/index.js
@@ -17,7 +17,7 @@ function isMusl() {
     }
   } else {
     const { glibcVersionRuntime } = process.report.getReport().header
-    return !glibcVersionRuntime
+    return !Boolean(glibcVersionRuntime)
   }
 }
 
diff --git packages/xxhash/index.d.ts packages/xxhash/index.d.ts
index aa136d3..0137e0f 100644
--- packages/xxhash/index.d.ts
+++ packages/xxhash/index.d.ts
@@ -10,7 +10,7 @@ export class ExternalObject<T> {
   }
 }
 export function xxh32(input: string | Buffer, seed?: number | undefined | null): number
-export function xxh64(input: string | Buffer, seed?: BigInt | undefined | null): BigInt
+export function xxh64(input: string | Buffer, seed?: bigint | undefined | null): bigint
 export class Xxh32 {
   constructor(seed?: number | undefined | null)
   update(input: string | Buffer): this
@@ -18,21 +18,21 @@ export class Xxh32 {
   reset(newState?: number | undefined | null): void
 }
 export class Xxh64 {
-  constructor(seed?: BigInt | undefined | null)
+  constructor(seed?: bigint | undefined | null)
   update(input: string | Buffer): this
-  digest(): BigInt
-  reset(newState?: BigInt | undefined | null): void
+  digest(): bigint
+  reset(newState?: bigint | undefined | null): void
 }
 export namespace xxh3 {
-  export function xxh64(input: string | Buffer, seed?: BigInt | undefined | null): BigInt
-  export function xxh64WithSecret(input: string | Buffer, secret: Buffer): BigInt
-  export function xxh128(input: string | Buffer, seed?: BigInt | undefined | null): BigInt
-  export function xxh128WithSecret(input: string | Buffer, secret: Buffer): BigInt
+  export function xxh64(input: string | Buffer, seed?: bigint | undefined | null): bigint
+  export function xxh64WithSecret(input: string | Buffer, secret: Buffer): bigint
+  export function xxh128(input: string | Buffer, seed?: bigint | undefined | null): bigint
+  export function xxh128WithSecret(input: string | Buffer, secret: Buffer): bigint
   export class Xxh3 {
-    static withSeed(seed?: BigInt | undefined | null): Xxh3
+    static withSeed(seed?: bigint | undefined | null): Xxh3
     static withSecret(secret: Buffer): Xxh3
     update(input: string | Buffer): this
-    digest(): BigInt
+    digest(): bigint
     reset(): void
   }
 }
diff --git packages/xxhash/index.js packages/xxhash/index.js
index 5dbcc44..51b683e 100644
--- packages/xxhash/index.js
+++ packages/xxhash/index.js
@@ -17,7 +17,7 @@ function isMusl() {
     }
   } else {
     const { glibcVersionRuntime } = process.report.getReport().header
-    return !glibcVersionRuntime
+    return !Boolean(glibcVersionRuntime)
   }
 }
 ```
