### ISSUE TITLE
Windows Server 2008R2下报错该如何解决？

### ISSUE THREAD

**Issue by enderahkin** [napi-rs/node-rs#632]
服务器：Windows Server 2008R2
node版本：v12.18.3
安装报错：
`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)`
启动报错：
`(node:4904) UnhandledPromiseRejectionWarning: Error: The specified module could
not be found.
\\?\F:\diffTest_server\node_modules\@node-rs\jieba\jieba.win32.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1187:18)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at loadBinding (F:\diffTest_server\node_modules\@node-rs\helper\lib\loader.j
s:27:12)
    at Object.<anonymous> (F:\diffTest_server\node_modules\@node-rs\jieba\index.
js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
(node:4904) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). To termina
te the node process on unhandled promise rejection, use the CLI flag `--unhandle
d-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejectio
ns_mode). (rejection id: 2)
(node:4904) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.`

**Comment by Brooooooklyn** [comment]
https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170 试一下安装最新的 msvc runtime？
