### ISSUE TITLE
SvelteKit 2 & Cloudflare Page: Could not resolve "@node-rs/argon2-wasm32-wasi"

### ISSUE THREAD

**Issue by Shyrogan** [napi-rs/node-rs#862]
I made a project to reproduce the error here:
https://github.com/Shyrogan/sveltekit-argon2-cf-error

```
> Using @sveltejs/adapter-cloudflare
✘ [ERROR] Could not resolve "@node-rs/argon2-wasm32-wasi"

    node_modules/@node-rs/argon2/browser.js:1:14:
      1 │ export * from '@node-rs/argon2-wasm32-wasi'
        ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@node-rs/argon2-wasm32-wasi" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.


error during build:
Error: Bundling with esbuild failed with 1 error
    at adapt (file:///Users/sebastienvial/Documents/transitions.ag/cloudflare-pages-sveltekit/node_modules/@sveltejs/adapter-cloudflare/index.js:134:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async adapt (file:///Users/sebastienvial/Documents/transitions.ag/cloudflare-pages-sveltekit/node_modules/@sveltejs/kit/src/core/adapt/index.js:38:2)
    at async finalise (file:///Users/sebastienvial/Documents/transitions.ag/cloudflare-pages-sveltekit/node_modules/@sveltejs/kit/src/exports/vite/index.js:890:7)
    at async Object.handler (file:///Users/sebastienvial/Documents/transitions.ag/cloudflare-pages-sveltekit/node_modules/@sveltejs/kit/src/exports/vite/index.js:920:5)
    at async PluginDriver.hookParallel (file:///Users/sebastienvial/Documents/transitions.ag/cloudflare-pages-sveltekit/node_modules/rollup/dist/es/shared/node-entry.js:19730:17)
    at async Object.close (file:///Users/sebastienvial/Documents/transitions.ag/cloudflare-pages-sveltekit/node_modules/rollup/dist/es/shared/node-entry.js:20665:13)
    at async build (file:///Users/sebastienvial/Documents/transitions.ag/cloudflare-pages-sveltekit/node_modules/vite/dist/node/chunks/dep-D8YhmIY-.js:65760:17)
    at async CAC.<anonymous> (file:///Users/sebastienvial/Documents/transitions.ag/cloudflare-pages-sveltekit/node_modules/vite/dist/node/cli.js:828:5)
```

**Comment by adumesny** [comment]
I have the same issue with esbuild (webpack was fine) using node v22. if I use an older v1.19.0 version that gives a bit more info

```

**Comment by adumesny** [comment]
X [ERROR] Could not resolve "path"

    node_modules/@node-rs/jieba/index.js:11:12:
      11 │ } = require('path');
         ╵             ~~~~~~

  The package "path" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.


X [ERROR] No loader is configured for ".node" files: node_modules/@node-rs/jieba-win32-x64-msvc/jieba.win32-x64-msvc.node

    node_modules/@node-rs/jieba/index.js:104:36:
      104 │ ...        nativeBinding = require('@node-rs/jieba-win32-x64-msvc');

**Comment by Brooooooklyn** [comment]
need to install `@node-rs/jieba-wasm32-wasi` or `@node-rs/argon2-wasm32-wasi` manually: `npm i @node-rs/argon2-wasm32-wasi`

**Comment by adumesny** [comment]
unfortunately no, I get (on windows x64). that looks like a 32bit image or something.... with the latest version it does install @node-rs/jieba-win32-x64-msvc (or linux version on our build machine) but then esbuild doesn't know how to load .node files.

`error @node-rs/jieba-wasm32-wasi@2.0.0: The CPU architecture "x64" is incompatible with this module.`

**Comment by Brooooooklyn** [comment]
@adumesny see https://github.com/napi-rs/node-rs/issues/792#issuecomment-1959141811 for the context

**Comment by adumesny** [comment]
sure I can install it locally, but then it tries to build or something and even if I add the VS missing stuff, how is that going to work on the linux build machine ??? can't be platform specific what I put in yarn.lock nor compile stuff here...

looks like I may have to take out the feature that depends indirectly on lunr-languages/lunr.zh then this lib.

```
> yarn add @node-rs/jieba-wasm32-wasi --ignore-platform

gyp ERR! find VS Failure details: undefined
gyp ERR! find VS not looking for VS2015 as it is only supported up to Node.js 18
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the \"Desktop development with C++\" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows

```

**Comment by adumesny** [comment]
and even when I force add I still get these errors, so back to square one
```
X [ERROR] No loader is configured for ".wasm" files: node_modules/@node-rs/jieba/node_modules/@node-rs/jieba-wasm32-wasi/jieba.wasm32-wasi.wasm?url

    node_modules/@node-rs/jieba/node_modules/@node-rs/jieba-wasm32-wasi/jieba.wasi-browser.js:2:22:
      2 │ import __wasmUrl from './jieba.wasm32-wasi.wasm?url';
        ╵                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


X [ERROR] Top-level await is not available in the configured target environment ("chrome128.0", "edge128.0", "firefox115.0", "ios17.0", "safari17.0" + 5 overrides)

    node_modules/@node-rs/jieba/node_modules/@node-rs/jieba-wasm32-wasi/jieba.wasi-browser.js:12:19:
      12 │ const __wasmFile = await fetch(__wasmUrl).then(res => res.arrayBuf...
         ╵                    ~~~~~


X [ERROR] This require call is not allowed because the transitive dependency "node_modules/@node-rs/jieba/node_modules/@node-rs/jieba-wasm32-wasi/jieba.wasi-browser.js" contains a top-level await

    node_modules/lunr-languages/lunr.zh.js:33:37:
      33 │     module.exports = factory(require('@node-rs/jieba'));
         ╵                                      ~~~~~~~~~~~~~~~~

  The file "node_modules/@node-rs/jieba/browser.js" imports the file "node_modules/@node-rs/jieba/node_modules/@node-rs/jieba-wasm32-wasi/jieba.wasi-browser.js" here:

    node_modules/@node-rs/jieba/browser.js:1:14:
      1 │ export * from '@node-rs/jieba-wasm32-wasi';
        ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The top-level await in "node_modules/@node-rs/jieba/node_modules/@node-rs/jieba-wasm32-wasi/jieba.wasi-browser.js" is here:

    node_modules/@node-rs/jieba/node_modules/@node-rs/jieba-wasm32-wasi/jieba.wasi-browser.js:12:19:
      12 │ const __wasmFile = await fetch(__wasmUrl).then(res => res.arrayBuf...
```

**Comment by TjenWellens** [comment]
fyi, I found a link [comment online](https://www.answeroverflow.com/m/1304500967726907512) says you can use `PBKDF2` instead of `argon2` ([but PBKDF2 is less secure](https://guptadeepak.com/comparative-analysis-of-password-hashing-algorithms-argon2-bcrypt-scrypt-and-pbkdf2/)?)

It also mentions a tutorial about using a [custom "Argon2 Rust Worker"](https://mli.puffinsystems.com/blog/lucia-auth-cloudflare-argon2)
No idea if such a thing is a good idea. But sounded interesting to put here for others to find.

**Comment by focus-at** [comment]
same problem for

`
01:54:38.033 | ✘ [ERROR] Build failed with 1 error:
-- | --
01:54:38.033 |  
01:54:38.033 | ✘ [ERROR] Could not resolve "@node-rs/jsonwebtoken-wasm32-wasi"
01:54:38.033 |  
01:54:38.033 | ../../node_modules/@node-rs/jsonwebtoken/browser.js:1:14:
01:54:38.033 | 1 │ export * from '@node-rs/jsonwebtoken-wasm32-wasi'
01:54:38.033 | ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
01:54:38.034 |  
01:54:38.034 | You can mark the path "@node-rs/jsonwebtoken-wasm32-wasi" as external to exclude it from the bundle, which will remove this error.
`

**Comment by antlossway** [comment]
anyone has solved the problem?

**Comment by TjenWellens** [comment]
My guess is this is not something that will be solved. At least not in the free tier of cloudflare workers.

Password hashing must be computationally expensive to be secure. Free tier must be cheap to be viable.

Unless what is 'computationally expensive' is actually not expensive to cloudflare, it's unlikely to be 'fixed' by cloudflare in the free tier. 

I ended up choosing externalizing auth to a SAAS provider, that does offer a free tier for low amount of users.

**Comment by antlossway** [comment]
I got this error while running `npm run build` locally, I'm using sveltekit2 and vite6.

`4:34:02 PM [vite] (client) error while updating dependencies:
Error: Build failed with 1 error:
node_modules/@node-rs/argon2/browser.js:1:14: ERROR: Could not resolve "@node-rs/argon2-wasm32-wasi"`

**Comment by karlos1337** [comment]
I solved this by adding 
```json
"compatibility_flags": ["nodejs_compat"]
```
To wrangler.jsonc file.

**Comment by victormihalache** [comment]
> I solved this by adding
> 
> "compatibility_flags": ["nodejs_compat"]
> To wrangler.jsonc file.

Did you also install `@node-rs/argon2-wasm32-wasi`?

**Comment by victormihalache** [comment]
If you install `@node-rs/argon2-wasm-wasi` (or the other one) you'll still get an error. [This issue seems to be from cloudflare's part](https://github.com/cloudflare/workers-sdk/issues/8405)

**Comment by Blackwidow-sudo** [comment]
I doubt that this issue is cloudflare specific because i have the same issues when i try to run the vite dev server in a sveltekit project while using the new "remote functions" from sveltekit. Even without that new feature i sometimes had issues, but now i always get these errors.

**Comment by lmorais-dev** [comment]
I'm having the same problem:

```
X [ERROR] Could not resolve "@node-rs/argon2-wasm32-wasi"

    node_modules/@node-rs/argon2/browser.js:1:14:
      1 │ export * from '@node-rs/argon2-wasm32-wasi'
        ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@node-rs/argon2-wasm32-wasi" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
```

No idea how to fix it. I'm using adapter-node and when I build it works fine. But `npm run dev` flags this error :(
